# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  pull_request:
    branches: [ "test" ]
  workflow_dispatch:

env:
  FRAMEWORK: net8.0-android
  CONFIGURATION: Release
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Android workload
      run: dotnet workload install android

    - name: Install Android platform tools
      run: $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --install platform-tools

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore
    - name: 上传构建文件
      uses: actions/upload-artifact@v4
      with:
        name: colormc
        path: |
          *.apk
