# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  pull_request:
    branches: [ "test" ]
  workflow_dispatch:
  push:

env:
  FRAMEWORK: net8.0-android
  CONFIGURATION: Release
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Android workload
      run: dotnet workload install android

    - name: Install Android platform tools
      run: $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --install platform-tools

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Publish Android
      run: |
          sed -i "s|package=\"coloryr.colormc.android\"|package=\"coloryr.colormc.android\"|g" src/ColorMC.Android/Properties/AndroidManifest.xml
          sed -i "s|<string name=\"displayName\" translatable=\"false\">ColorMC</string>|<string name=\"displayName\" translatable=\"false\">ColorMC</string>|g" src/ColorMC.Android/Resources/values/string.xml

          dotnet publish -f:$FRAMEWORK -c:$CONFIGURATION --no-restore src/ColorMC.Android/ColorMC.Android.csproj
          
    - name: 上传构建文件
      uses: actions/upload-artifact@v4
      with:
        name: colormc
        path: |
          *.apk
