# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: set up JDK 17
      uses: actions/setup-java@main
      with:
        distribution: 'dragonwell'
        java-version: '17'
    - name: Build
      run: dotnet build --no-restore
    - name: 上传构建文件
      uses: actions/upload-artifact@v4
      with:
        name: colormc
        path: build_out/
